name: 🐞 Bug Report
description: Bạn đang gặp lỗi 😐
title: "🐛 "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Mô tả lỗi
      placeholder: Bạn gặp lỗi đếch gì voại? 🥱
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: 💻 Hệ điều hành
      description: |
        Chọn hệ điều hành bạn đang sử dụng
      options:
        - label: Windows
        - label: macOS
        - label: Linux
        - label: Android
        - label: iOS / iPadOS
        - label: Khác
  - type: textarea
    id: other-os
    attributes:
      label: 🖥️ Hệ điều hành khác
      description: |
        Nếu bạn chọn "Khác" ở trên, hãy điền tên hệ điều hành bạn đang sử dụng
      placeholder: "Ví dụ: Ubuntu, Arch Linux, Manjaro, Cục gạch Nokia..."
    validations:
      required: false
  - type: checkboxes
    id: browser
    attributes:
      label: 🌏 Trình duyệt
      description: |
        Chọn trình duyệt bạn đang sử dụng
      options:
        - label: Chrome
        - label: Firefox
        - label: Edge
        - label: Safari
        - label: Opera
        - label: Khác
  - type: textarea
    id: other-browser
    attributes:
      label: 👽 Trình duyệt khác
      description: |
        Nếu bạn chọn "Khác" ở trên, hãy điền tên trình duyệt bạn đang sử dụng
      placeholder: "Ví dụ: Brave, Vivaldi, Kiwi,..."
  - type: textarea
    id: note
    attributes:
      label: 📝 Ghi chú
      placeholder: Bạn có ghi chú gì thêm không?
    validations:
      required: false