name: 🙏 Update Request
description: Cập nhật khi website trường có thay đổi
title: "🔨 Cập nhật UserScript <-> UIT website"
labels: ["uit-update"]
body:
  - type: markdown
    attributes:
      value: |
        Vui lòng giữ nguyên tiêu đề, không thay đổi ‼️
  - type: textarea
    id: update-description
    attributes:
      label: 🔨 Mô tả cập nhật
      placeholder: |
        Bạn có thể mô tả cụ thể hơn về sự thay đổi cập nhật này không?
        Hoặc cụ thể ví dụ như element, tag, class, id, ... thay đổi.
    validations:
      required: false
  - type: dropdown
    id: still-working
    attributes:
      label: 🤥 Script vẫn hoạt động?
      description: |
        Hiện tại version mới nhất vẫn còn hoạt động?
      options:
        - Co
        - Cothedeonaoduoc
    validations:
      required: true