name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello. Có thể Kevin Nitro sẽ rep sớm thôi. Chờ tẹo nha 😴"
        pr-message: "Bro có chắc là nó chạy không mà PR vậy 😶‍🌫️"
